### ISSUE TITLE
Assignment feeback

### ISSUE THREAD

**Issue by MD-AZMAL** [shashankbhosagi/Secure-file-sharing-backend#1]
Please change the project name to something else. Using company name as the repository is not the best practice and gives wrong impression in opensource regarding the company

**Comment by shashankbhosagi** [comment]
Feedback noted 
changed the repo name to Secure-file-sharing-backend

**Comment by MD-AZMAL** [comment]
1. instead of hardcoding the types in users and encryptedFiles you could have used Interfaces which is best practice, please make the necessary changes
2. Add a check for username exists in addUser controller
3. in GET request you are using request body, ideally request body is not used for get request, try passing the required info using HEADERS, Query params, or Route params
4. While adding the user to the file, you could also ask for the owner username and check if the right owner is giving access to other user, otherwise any user can make a request to add files and get users added to files that he doesnt own. For the scope of this project it seems fine for now, but if you can add the owner level check that would be great. Give it a shot!, try passing the owner username in HEADER instead of body or params

Let me know once you've done the changes, I'll check and let you know

@shashankbhosagi

**Comment by shashankbhosagi** [comment]
Did the following changes to application

- [x] Added Interfaces for `users` and `encryptedFiles`
- [x] Added Checks for username exists in `addUser` controller
- [x] Updated GET requests to use HEADERS, query params
- [x] Added `owner-username` in `header` and checks also to ensure only owner can give access rights to other user

@MD-AZMAL

**Comment by MD-AZMAL** [comment]
Excellent!
